author: Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: Text::Quoted
name: Text-Quoted
no_index: 
  directory: 
    - inc
    - t
requires: 
  Text::Autoformat: 0
  Text::Tabs: 0
version: 2.02
