--- 
abstract: Extract the structure of a quoted mail message
author: 
  - Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-Quoted
no_index: 
  directory: 
    - inc
    - t
requires: 
  Text::Autoformat: 0
  Text::Tabs: 0
  perl: 5.6.0
version: 2.03
